name: CI
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.4.0
      # Install Deps
      - run: npm install
      # Build
      - run: npm run build
      # Add files that were created during a run, e.g. created files from style dictionary or token-transformer.
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "[auto-commit] Update Tokens - ${{ github.event.head_commit.message }}"
      # Purges cache for dist
      - run: node utils/purgeDist
