name: Build Tokens From Figma Changes
on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.4.0
      # Install Deps
      - run: npm install
      # Build
      - run: npm run build
      - name: Add timestamp to build if there were changes
        run: if [ "$(git diff)" ]; then echo $(date) > dist/build-date.txt; else echo 0;fi
      # Add files that were created during a run, e.g. created files from style dictionary or token-transformer.
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "[auto-commit] Update Tokens - ${{ github.event.head_commit.message }}"
      # Purges cache for dist
      - run: node build-utils/purgeDist
